languageCode = "en-us"
title = "steverusso.me"
theme = "hugo-theme-essential"

[frontmatter]
	publishDate = [ "published" ]
	lastmod = [ ":git", "lastmod" ]

[markup.goldmark.renderer]
	unsafe= true

[params]
	stylesheets = [ "main.css" ]
	favicon = "/img/avatar.png"
	logo = "/img/avatar.png"
	[params.drawer]
		disableSectionLinks = true
